DROP TABLE IF EXISTS LORDS;
DROP TABLE IF EXISTS PLANETS;

CREATE TABLE LORDS (
id BIGINT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(250) NOT NULL,
age INT NOT NULL,
CONSTRAINT AK_LORD_NAME UNIQUE(name)
);

CREATE TABLE PLANETS (
id BIGINT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(250) NOT NULL,
lord_id BIGINT,
CONSTRAINT AK_PLANET_NAME UNIQUE(name)
);

ALTER TABLE PLANETS
    ADD FOREIGN KEY (lord_id)
    REFERENCES LORDS(id);